server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
  servlet:
    multipart:
      max-file-size: 10240000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
reggie:
#  path: D:\software\reggie_task_out\src\main\resources\static\common\download\
#  pathCache: D:\software\reggie_task_out\src\main\resources\static\common\download\cache\
  path: D:\software\reggieImage\
  pathCache: D:\software\reggieImage\cache\
